---
# This playbook deploys ACHE using docker

- name: Config Python 2 on all servers
  hosts: ache
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: 'Install Python2'
      raw: apt-get -y install python-minimal

- hosts: ache
  remote_user: ubuntu
  tasks: []

- name: Install Docker
  hosts: ache
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - docker

- name: Deploy ACHE Crawler
  hosts: ache
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - role: ache
      ache_crawler_id: "default"
      ache_config:
        link_storage.link_strategy.use_scope: true
        link_storage.link_classifier.type: MaxDepthLinkClassifier
        link_storage.link_classifier.max_depth: 299
        link_storage.link_selector: MaximizeWebsitesLinkSelector
        link_storage.scheduler.host_min_access_interval: 5000
        link_storage.download_sitemap_xml: true
        link_storage.recrawl_selector: SitemapsRecrawlSelector
        link_storage.recrawl_selector.sitemaps.interval: 86400 # every 24h
        link_storage.disallow_sites_in_robots_file: false
        crawler_manager.downloader.user_agent.name: ACHE
        crawler_manager.downloader.user_agent.url: https://github.com/ViDA-NYU/ache
        crawler_manager.downloader.use_okhttp3_fetcher: true
